# Settings in the [build] context are global and are applied to all contexts
# unless otherwise overridden by more specific contexts.
[build]
  # Directory to change to before starting a build.
  # This is where we will look for package.json/.nvmrc/etc.
  # If not set, defaults to the root directory.
  publish = "public/"

[functions]
  # Directory with serverless functions, including background functions,
  # to deploy. This is relative to the base directory if one has been set, 
  # or the root directory if a base hasn’t been set.
  directory = "functions/"

[functions."test-preload-batch-auto-background"]
schedule = "55 15 * * *"

[functions."test-activate-batch-auto-background"]
schedule = "55 3 * * *"

[functions."preload-batch-auto-background"]
schedule = "55 15 * * 1"

[functions."activate-batch-auto-background"]
schedule = "55 3 * * 1"
