name: Black Box Batch Testing Activate
on:
  workflow_dispatch:
  schedule:
    - cron: '55 3 * * *'
jobs:
  batch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: npm ci
      - name: Activate Batch
        run: |
          ts-node -e "import { handle } from './functions/activate-batch-auto-background'; handle()"
        env:
          ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
          SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
          INFURA_API_KEY: ${{ secrets.TESTING_INFURA_API_KEY }}
          REGION: ${{ secrets.REGION_TESTING }}
