name: Preload Batch Testing
on:
  schedule:
    - cron: '0 4 * * *'
jobs:
  batch:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: npm ci
    - name: Batch
      run: |
        node -e 'require("./functions/preload-batch-background").handle({ batch:"cron" })'
        node -e 'require("./functions/activate-batch-background").handle({ batch:"cron" })'
      env:
        ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
        SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
        INFURA_API_KEY: ${{ secrets.TESTING_INFURA_API_KEY }}
        REGION: ${{ secrets.REGION_TESTING }}
